### ISSUE TITLE
Search_lib.py

### ISSUE THREAD

**Issue by Radhu903** [Radhu903/Git_Learning-#2]

**Comment by Radhu903** [comment]
```
C:\ProgramData\Anaconda3\python.exe C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
Traceback (most recent call last):
  File "C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py", line 351, in <module>
    main()
  File "C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py", line 343, in main
    AmiSearch.test_sect_dicts()
  File "C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py", line 160, in test_sect_dicts
    ami_search = AmiSearch()
  File "C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py", line 46, in __init__
    self.ami_projects = AmiProjects()
  File "C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py", line 205, in __init__
    self.create_project_dict()
  File "C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py", line 209, in create_project_dict
    self.add_with_check(AmiProjects.LIION10, os.path.join(PHYSCHEM_RESOURCES, "liion10"))
  File "C:/Users/DELL/Radhu/openDiagram/physchem/python/search_lib.py", line 215, in add_with_check
    Util.check_exists(file)
  File "C:\Users\DELL\Radhu\openDiagram\physchem\python\util.py", line 291, in check_exists
    assert os.path.exists(file), str(file) + " should exist"
AssertionError: C:\Users\DELL\projects\openDiagram\physchem\resources\liion10 should exist
running search main
dicts None
sects None

Process finished with exit code 1
```
